### ISSUE TITLE
追踪问题

### ISSUE THREAD

**Issue by FishHe** [chenjianqu/Solov2-TensorRT-CPP#1]
感谢作者分享代码~
在追踪模块的运动参数滤波部分，使用的卡尔曼滤波模型和原始论文不一致：
https://github.com/chenjianqu/Tracking-Solov2-Deepsort/blob/master/InstanceTracking/KalmanTracker.cpp
计算匹配测度（目标相似性和几何距离）时，有时测度为负值。

同样的实现来自这里：
https://github.com/weixu000/libtorch-yolov3-deepsort

和原始 DeepSort-Python 相比，追踪结果不能和原始算法对齐。

**Comment by chenjianqu** [comment]
我这里也是直接使用了&nbsp;libtorch-yolov3-deepsort&nbsp;的实现。这个代码中卡尔曼滤波的实现其实是参考了SORT论文，状态空间与DeepSORT的略有不同。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenjianqu/Solov2-TensorRT-CPP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 下午2:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenjianqu/Solov2-TensorRT-CPP] 追踪问题 (Issue #1)





 
感谢作者分享代码~
 在追踪模块的运动参数滤波部分，使用的卡尔曼滤波模型和原始论文不一致：
 https://github.com/chenjianqu/Tracking-Solov2-Deepsort/blob/master/InstanceTracking/KalmanTracker.cpp
 计算匹配测度（目标相似性和几何距离）时，有时测度为负值。
 
同样的实现来自这里：
 https://github.com/weixu000/libtorch-yolov3-deepsort
 
和原始 DeepSort-Python 相比，追踪结果不能和原始算法对齐。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
